version: "3.7"
networks:
  app-tier:
    driver: bridge
services:
  zookeeper-test:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-test:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka-test:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-test:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-test:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper-test
    networks:
      - app-tier

  laravel:
    build:
      context: .
      dockerfile: dev/Dockerfile
    entrypoint: /application/laravel-kafka/start.sh
    environment:
      KAFKA_BROKERS: kafka-test:9092
    volumes:
      - .:/application/laravel-kafka
      - ./tests:/application/laravel-test/tests
      - ./src:/application/laravel-test/src
    networks:
      - app-tier